### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by sagikazarmark** [mattermost/xml-roundtrip-validator#8]
Now that the vulnerabilities are publicly disclosed, maybe tagging a version of this package would make sense. Even if you don't want to have backward compatibility promise for now, following tagged versions with 0 major version is easier than tracking commit hashes.

**Comment by jupenur** [comment]
Thanks @sagikazarmark, totally agreed. Tagged [v0.1.0](https://github.com/mattermost/xml-roundtrip-validator/tags).

**Comment by sagikazarmark** [comment]
Thanks!
