### ISSUE TITLE
Does not seem to validate XML properly for GO 1.17

### ISSUE THREAD

**Issue by ameade** [mattermost/xml-roundtrip-validator#9]
The unittests do not pass in go 1.17 but they all pass in 1.16. I Discovered this running unittests for my project after updating Golang that has been using this library for some time.

Unittest results.
=== RUN   TestValidateZippedReader
    reader_test.go:42:
        	Error Trace:	reader_test.go:42
        	Error:      	An error is expected but got nil.
        	Test:       	TestValidateZippedReader
        	Messages:   	Should error on an invalid XML document
--- FAIL: TestValidateZippedReader (0.00s)
=== RUN   TestValidXML
--- PASS: TestValidXML (0.00s)
=== RUN   TestColonsInLocalNames
    validator_test.go:41:
        	Error Trace:	validator_test.go:41
        	Error:      	An error is expected but got nil.
        	Test:       	TestColonsInLocalNames
        	Messages:   	Should error on input with colons in the root element's name
--- FAIL: TestColonsInLocalNames (0.00s)
=== RUN   TestEmptyNames
    validator_test.go:73:
        	Error Trace:	validator_test.go:73
        	Error:      	An error is expected but got nil.
        	Test:       	TestEmptyNames
        	Messages:   	Should error on start element with no local name
--- FAIL: TestEmptyNames (0.00s)
=== RUN   TestEmptyAttributes
    validator_test.go:83:
        	Error Trace:	validator_test.go:83
        	Error:      	An error is expected but got nil.
        	Test:       	TestEmptyAttributes
        	Messages:   	Should error on input with empty attribute names
--- FAIL: TestEmptyAttributes (0.00s)
=== RUN   TestDirectives
    validator_test.go:115:
        	Error Trace:	validator_test.go:115
        	Error:      	An error is expected but got nil.
        	Test:       	TestDirectives
        	Messages:   	Should error on bad directive
--- FAIL: TestDirectives (0.00s)
=== RUN   TestUnparseableXML
    validator_test.go:151:
        	Error Trace:	validator_test.go:151
        	Error:      	"[XML syntax error on line 1: unescaped ]]> not in CDATA section]" should have 2 item(s), but has 1
        	Test:       	TestUnparseableXML
        	Messages:   	Should return exactly two errors
--- FAIL: TestUnparseableXML (0.00s)
=== RUN   TestValidateAll
    validator_test.go:162:
        	Error Trace:	validator_test.go:162
        	Error:      	Not equal:
        	            	expected: 3
        	            	actual  : 0
        	Test:       	TestValidateAll
        	Messages:   	Should return three errors
--- FAIL: TestValidateAll (0.00s)
=== RUN   TestTokenEquals
--- PASS: TestTokenEquals (0.00s)
=== RUN   TestErrorMessages
--- PASS: TestErrorMessages (0.00s)
FAIL
FAIL	github.com/mattermost/xml-roundtrip-validator	0.007s
FAIL

**Comment by ameade** [comment]
If I had to guess, it's related to this: https://go.dev/doc/go1.17

```
encoding/xml
When a comment appears within a Directive, it is now replaced with a single space instead of being completely elided.

**Invalid element or attribute names with leading, trailing, or multiple colons are now stored unmodified into the Name.Local field.**
```

**Comment by jupenur** [comment]
Thanks @ameade! The validation should still be working correctly, it's just that Go 1.17 fixes some of the inconsistencies the tests assume to be there.

I already fixed the tests in my local branch and will open a PR as soon as we figure out a permission issue on GitHub.
